version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/book-database
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - ./volumes/mongo:/data/db   
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
